# Generated by Django 3.2 on 2024-08-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_shoppinglist_unique_shopping_list'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingridientrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredients'), name='unique_recipe_ingredients'),
        ),
    ]
