# Generated by Django 3.2 on 2024-08-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_ingridientrecipe_unique_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='rescipes/images/', verbose_name='Изображение'),
        ),
    ]
