# Generated by Django 3.2 on 2024-10-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_shoppinglist_shoppingcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='_ingredients',
        ),
    ]
