# Generated by Django 3.2 on 2024-10-06 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_rename__ingredients_recipe_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLinkConverter',
            fields=[
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recipes.recipe', verbose_name='Рецепт')),
                ('short_link', models.CharField(db_index=True, editable=False, max_length=3, unique=True, verbose_name='Короткая ссылка')),
            ],
            options={
                'verbose_name': 'Конвентатор коротких ссылок',
                'verbose_name_plural': 'Конвентаторы коротких ссылок',
            },
        ),
    ]
