# Generated by Django 3.2 on 2024-10-08 12:00

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_shortlinkconverter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=recipes.models.image_directory_path, verbose_name='Изображение'),
        ),
    ]
